// This code was generated by Hypar.
// Edits to this code will be overwritten the next time you run 'hypar init'.
// DO NOT EDIT THIS FILE.

using Elements;
using Elements.GeoJSON;
using Elements.Geometry;
using Elements.Geometry.Solids;
using Elements.Validators;
using Elements.Serialization.JSON;
using Hypar.Functions;
using Hypar.Functions.Execution;
using Hypar.Functions.Execution.AWS;
using System;
using System.Collections.Generic;
using System.Linq;
using Line = Elements.Geometry.Line;
using Polygon = Elements.Geometry.Polygon;

namespace CutAndFill
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "10.1.21.0 (Newtonsoft.Json v12.0.0.0)")]
    
    public  class CutAndFillInputs : S3Args
    
    {
        [Newtonsoft.Json.JsonConstructor]
        
        public CutAndFillInputs(Polygon @sitePerimeter, IList<Polygon> @perimeters, double @elevation, double @batterAngle, string bucketName, string uploadsBucket, Dictionary<string, string> modelInputKeys, string gltfKey, string elementsKey, string ifcKey):
        base(bucketName, uploadsBucket, modelInputKeys, gltfKey, elementsKey, ifcKey)
        {
            var validator = Validator.Instance.GetFirstValidatorForType<CutAndFillInputs>();
            if(validator != null)
            {
                validator.PreConstruct(new object[]{ @sitePerimeter, @perimeters, @elevation, @batterAngle});
            }
        
            this.SitePerimeter = @sitePerimeter;
            this.Perimeters = @perimeters;
            this.Elevation = @elevation;
            this.BatterAngle = @batterAngle;
        
            if(validator != null)
            {
                validator.PostConstruct(this);
            }
        }
    
        /// <summary>The perimeter of the site.</summary>
        [Newtonsoft.Json.JsonProperty("Site Perimeter", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public Polygon SitePerimeter { get; set; }
    
        /// <summary>The perimeters of the cut and fill areas.</summary>
        [Newtonsoft.Json.JsonProperty("Perimeters", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public IList<Polygon> Perimeters { get; set; }
    
        /// <summary>The elevation of the final site relative to the site origin.</summary>
        [Newtonsoft.Json.JsonProperty("Elevation", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double Elevation { get; set; } = 0D;
    
        /// <summary>The angle of fill battering in degrees.</summary>
        [Newtonsoft.Json.JsonProperty("Batter Angle", Required = Newtonsoft.Json.Required.DisallowNull, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
        public double BatterAngle { get; set; } = 45D;
    
    
    }
}